package ca.mcgill.sis.dmas.kam1n0.framework.disassembly;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

public class LibcUtils {

	public static final Set<String> c_calls = Arrays.asList("*pthread_getspecific", "*sbrk", "*sem_open", "__fbufsize",
			"__flbf", "__fpending", "__fpurge", "__freadable", "__freading", "__fsetlocking", "__fwritable",
			"__fwriting", "__ppc_get_timebase", "__ppc_get_timebase_freq", "__ppc_mdoio", "__ppc_mdoom",
			"__ppc_set_ppr_low", "__ppc_set_ppr_med", "__ppc_set_ppr_med_high", "__ppc_set_ppr_med_low",
			"__ppc_set_ppr_very_low", "__ppc_yield", "__va_copy", "_exit", "_exit", "_flushlbf", "_tolower", "_toupper",
			"a64l", "abort", "abs", "accept", "access", "acos", "acosf", "acosfn", "acosfnx", "acosh", "acoshf",
			"acoshfn", "acoshfnx", "acoshl", "acosl", "addmntent", "addseverity", "adjtime", "adjtimex", "aio_cancel",
			"aio_cancel64", "aio_error", "aio_error64", "aio_fsync", "aio_fsync64", "aio_init", "aio_read",
			"aio_read64", "aio_return", "aio_return64", "aio_suspend", "aio_suspend64", "aio_write", "aio_write64",
			"alarm", "aligned_alloc", "alloca", "alphasort", "alphasort64", "argp_error", "argp_failure", "argp_help",
			"argp_parse", "argp_state_help", "argp_usage", "argz_add", "argz_add_sep", "argz_append", "argz_count",
			"argz_create", "argz_create_sep", "argz_delete", "argz_extract", "argz_insert", "argz_next", "argz_replace",
			"argz_stringify", "asctime", "asctime_r", "asin", "asinf", "asinfn", "asinfnx", "asinh", "asinhf",
			"asinhfn", "asinhfnx", "asinhl", "asinl", "asprintf", "assert", "assert_perror", "atan", "atan2", "atan2f",
			"atan2fn", "atan2fnx", "atan2l", "atanf", "atanfn", "atanfnx", "atanh", "atanhf", "atanhfn", "atanhfnx",
			"atanhl", "atanl", "atexit", "atof", "atoi", "atol", "atoll", "backtrace", "backtrace_symbols",
			"backtrace_symbols_fd", "basename", "basename", "bcmp", "bcopy", "bind", "bind_textdomain_codeset",
			"bindtextdomain", "brk", "bsearch", "btowc", "bzero", "cabs", "cabsf", "cabsfn", "cabsfnx", "cabsl",
			"cacos", "cacosf", "cacosfn", "cacosfnx", "cacosh", "cacoshf", "cacoshfn", "cacoshfnx", "cacoshl", "cacosl",
			"calloc", "canonicalize", "canonicalize_file_name", "canonicalizef", "canonicalizefn", "canonicalizefnx",
			"canonicalizel", "carg", "cargf", "cargfn", "cargfnx", "cargl", "casin", "casinf", "casinfn", "casinfnx",
			"casinh", "casinhf", "casinhfn", "casinhfnx", "casinhl", "casinl", "catan", "catanf", "catanfn", "catanfnx",
			"catanh", "catanhf", "catanhfn", "catanhfnx", "catanhl", "catanl", "catclose", "catgets", "catopen",
			"cbc_crypt", "cbrt", "cbrtf", "cbrtfn", "cbrtfnx", "cbrtl", "ccos", "ccosf", "ccosfn", "ccosfnx", "ccosh",
			"ccoshf", "ccoshfn", "ccoshfnx", "ccoshl", "ccosl", "ceil", "ceilf", "ceilfn", "ceilfnx", "ceill", "cexp",
			"cexpf", "cexpfn", "cexpfnx", "cexpl", "cfgetispeed", "cfgetospeed", "cfmakeraw", "cfsetispeed",
			"cfsetospeed", "cfsetspeed", "chdir", "chmod", "chmod", "chown", "cimag", "cimagf", "cimagfn", "cimagfnx",
			"cimagl", "clearenv", "clearerr", "clearerr_unlocked", "clock", "clog", "clog10", "clog10f", "clog10fn",
			"clog10fnx", "clog10l", "clogf", "clogfn", "clogfnx", "clogl", "close", "closedir", "closelog", "confstr",
			"conj", "conjf", "conjfn", "conjfnx", "conjl", "connect", "continue", "copysign", "copysignf", "copysignfn",
			"copysignfnx", "copysignl", "cos", "cosf", "cosfn", "cosfnx", "cosh", "coshf", "coshfn", "coshfnx", "coshl",
			"cosl", "cpow", "cpowf", "cpowfn", "cpowfnx", "cpowl", "cproj", "cprojf", "cprojfn", "cprojfnx", "cprojl",
			"cpu_clr", "cpu_isset", "cpu_set", "cpu_zero", "creal", "crealf", "crealfn", "crealfnx", "creall", "creat",
			"creat64", "crypt", "crypt_r", "csin", "csinf", "csinfn", "csinfnx", "csinh", "csinhf", "csinhfn",
			"csinhfnx", "csinhl", "csinl", "csqrt", "csqrtf", "csqrtfn", "csqrtfnx", "csqrtl", "ctan", "ctanf",
			"ctanfn", "ctanfnx", "ctanh", "ctanhf", "ctanhfn", "ctanhfnx", "ctanhl", "ctanl", "ctermid", "ctime",
			"ctime_r", "cuserid", "dcgettext", "dcngettext", "des_failed", "des_setparity", "dgettext", "difftime",
			"dirfd", "dirname", "div", "dngettext", "drand48", "drand48_r", "drem", "dremf", "dreml", "dttoif", "dup",
			"dup2", "ecb_crypt", "ecvt", "ecvt_r", "encrypt", "encrypt_r", "endfsent", "endgrent", "endhostent",
			"endmntent", "endnetent", "endnetgrent", "endprotoent", "endpwent", "endservent", "endutent", "endutxent",
			"envz_add", "envz_entry", "envz_get", "envz_merge", "envz_remove", "envz_strip", "erand48", "erand48_r",
			"erf", "erfc", "erfcf", "erfcfn", "erfcfnx", "erfcl", "erff", "erffn", "erffnx", "erfl", "err", "error",
			"error_at_line", "errx", "execl", "execle", "execlp", "execv", "execve", "execvp", "exit", "exp", "exp10",
			"exp10f", "exp10fn", "exp10fnx", "exp10l", "exp2", "exp2f", "exp2fn", "exp2fnx", "exp2l", "expf", "expfn",
			"expfnx", "expl", "explicit_bzero", "expm1", "expm1f", "expm1fn", "expm1fnx", "expm1l", "fabs", "fabsf",
			"fabsfn", "fabsfnx", "fabsl", "fchdir", "fchmod", "fchown", "fclose", "fcloseall", "fcntl", "fcvt",
			"fcvt_r", "fd_clr", "fd_isset", "fd_set", "fd_zero", "fdatasync", "fdim", "fdimf", "fdimfn", "fdimfnx",
			"fdiml", "fdopen", "fdopendir", "feclearexcept", "fedisableexcept", "feenableexcept", "fegetenv",
			"fegetexcept", "fegetexceptflag", "fegetmode", "fegetround", "feholdexcept", "feof", "feof_unlocked",
			"feraiseexcept", "ferror", "ferror_unlocked", "fesetenv", "fesetexcept", "fesetexceptflag", "fesetmode",
			"fesetround", "fetestexcept", "fetestexceptflag", "feupdateenv", "fflush", "fflush_unlocked", "fgetc",
			"fgetc_unlocked", "fgetgrent", "fgetgrent_r", "fgetpos", "fgetpos64", "fgetpwent", "fgetpwent_r", "fgets",
			"fgets_unlocked", "fgetwc", "fgetwc_unlocked", "fgetws", "fgetws_unlocked", "fileno", "fileno_unlocked",
			"finite", "finitef", "finitel", "flockfile", "floor", "floorf", "floorfn", "floorfnx", "floorl", "fma",
			"fmaf", "fmafn", "fmafnx", "fmal", "fmax", "fmaxf", "fmaxfn", "fmaxfnx", "fmaxl", "fmaxmag", "fmaxmagf",
			"fmaxmagfn", "fmaxmagfnx", "fmaxmagl", "fmemopen", "fmin", "fminf", "fminfn", "fminfnx", "fminl", "fminmag",
			"fminmagf", "fminmagfn", "fminmagfnx", "fminmagl", "fmod", "fmodf", "fmodfn", "fmodfnx", "fmodl", "fmtmsg",
			"fnmatch", "fopen", "fopen64", "fopencookie", "fork", "forkpty", "fpathconf", "fpclassify", "fprintf",
			"fputc", "fputc_unlocked", "fputs", "fputs_unlocked", "fputwc", "fputwc_unlocked", "fputws",
			"fputws_unlocked", "fread", "fread_unlocked", "free", "freopen", "freopen64", "frexp", "frexpf", "frexpfn",
			"frexpfnx", "frexpl", "fromfp", "fromfpf", "fromfpfn", "fromfpfnx", "fromfpl", "fromfpx", "fromfpxf",
			"fromfpxfn", "fromfpxfnx", "fromfpxl", "fscanf", "fseek", "fseeko", "fseeko64", "fsetpos", "fsetpos64",
			"fstat", "fstat64", "fsync", "ftell", "ftello", "ftello64", "ftruncate", "ftruncate64", "ftrylockfile",
			"ftw", "ftw64", "funlockfile", "futimes", "fwide", "fwprintf", "fwrite", "fwrite_unlocked", "fwscanf",
			"gamma", "gammaf", "gammal", "gcvt", "get_avphys_pages", "get_current_dir_name", "get_nprocs",
			"get_nprocs_conf", "get_phys_pages", "getauxval", "getc", "getc_unlocked", "getchar", "getchar_unlocked",
			"getcontext", "getcwd", "getdate", "getdate_r", "getdelim", "getdomainnname", "getegid", "getentropy",
			"getenv", "geteuid", "getfsent", "getfsfile", "getfsspec", "getgid", "getgrent", "getgrent_r", "getgrgid",
			"getgrgid_r", "getgrnam", "getgrnam_r", "getgrouplist", "getgroups", "gethostbyaddr", "gethostbyaddr_r",
			"gethostbyname", "gethostbyname_r", "gethostbyname2", "gethostbyname2_r", "gethostent", "gethostid",
			"gethostname", "getitimer", "getline", "getloadavg", "getlogin", "getmntent", "getmntent_r", "getnetbyaddr",
			"getnetbyname", "getnetent", "getnetgrent", "getnetgrent_r", "getopt", "getopt_long", "getopt_long_only",
			"getpagesize", "getpass", "getpayload", "getpayloadf", "getpayloadfn", "getpayloadfnx", "getpayloadl",
			"getpeername", "getpgid", "getpgrp", "getpid", "getppid", "getpriority", "getprotobyname",
			"getprotobynumber", "getprotoent", "getpt", "getpwent", "getpwent_r", "getpwnam", "getpwnam_r", "getpwuid",
			"getpwuid_r", "getrandom", "getrlimit", "getrlimit64", "getrusage", "gets", "getservbyname",
			"getservbyport", "getservent", "getsid", "getsockname", "getsockopt", "getsubopt", "gettext",
			"gettimeofday", "getuid", "getumask", "getutent", "getutent_r", "getutid", "getutid_r", "getutline",
			"getutline_r", "getutmp", "getutmpx", "getutxent", "getutxid", "getutxline", "getw", "getwc",
			"getwc_unlocked", "getwchar", "getwchar_unlocked", "getwd", "glob", "glob64", "globfree", "globfree64",
			"gmtime", "gmtime_r", "grantpt", "grantpt", "gsignal", "gtty", "hasmntopt", "hcreate", "hcreate_r",
			"hdestroy", "hdestroy_r", "hsearch", "hsearch_r", "htonl", "htons", "hypot", "hypotf", "hypotfn",
			"hypotfnx", "hypotl", "iconv", "iconv_close", "iconv_open", "if_freenameindex", "if_indextoname",
			"if_nameindex", "if_nametoindex", "iftodt", "ilogb", "ilogbf", "ilogbfn", "ilogbfnx", "ilogbl", "imaxabs",
			"imaxdiv", "index", "inet_addr", "inet_aton", "inet_lnaof", "inet_makeaddr", "inet_netof", "inet_network",
			"inet_ntoa", "inet_ntop", "inet_pton", "initgroups", "initstate", "initstate_r", "innetgr", "ioctl",
			"isalnum", "isalpha", "isascii", "isatty", "isblank", "iscanonical", "iscntrl", "isdigit", "iseqsig",
			"isfinite", "isgraph", "isgreater", "isgreaterequal", "isinf", "isinff", "isinfl", "isless", "islessequal",
			"islessgreater", "islower", "isnan", "isnan", "isnanf", "isnanl", "isnormal", "isprint", "ispunct",
			"issignaling", "isspace", "issubnormal", "isunordered", "isupper", "iswalnum", "iswalpha", "iswblank",
			"iswcntrl", "iswctype", "iswdigit", "iswgraph", "iswlower", "iswprint", "iswpunct", "iswspace", "iswupper",
			"iswxdigit", "isxdigit", "iszero", "j0", "j0f", "j0fn", "j0fnx", "j0l", "j1", "j1f", "j1fn", "j1fnx", "j1l",
			"jn", "jnf", "jnfn", "jnfnx", "jnl", "jrand48", "jrand48_r", "kill", "killpg", "l64a", "labs", "lcong48",
			"lcong48_r", "ldexp", "ldexpf", "ldexpfn", "ldexpfnx", "ldexpl", "ldiv", "lfind", "lgamma", "lgamma_r",
			"lgammaf", "lgammaf_r", "lgammafn", "lgammafn_r", "lgammafnx", "lgammafnx_r", "lgammal", "lgammal_r",
			"link", "lio_listio", "lio_listio64", "listen", "llabs", "lldiv", "llogb", "llogbf", "llogbfn", "llogbfnx",
			"llogbl", "llrint", "llrintf", "llrintfn", "llrintfnx", "llrintl", "llround", "llroundf", "llroundfn",
			"llroundfnx", "llroundl", "localeconv", "localtime", "localtime_r", "log", "log10", "log10f", "log10fn",
			"log10fnx", "log10l", "log1p", "log1pf", "log1pfn", "log1pfnx", "log1pl", "log2", "log2f", "log2fn",
			"log2fnx", "log2l", "logb", "logbf", "logbfn", "logbfnx", "logbl", "logf", "logfn", "logfnx", "login",
			"login_tty", "logl", "logout", "logwtmp", "longjmp", "lrand48", "lrand48_r", "lrint", "lrintf", "lrintfn",
			"lrintfnx", "lrintl", "lround", "lroundf", "lroundfn", "lroundfnx", "lroundl", "lsearch", "lseek",
			"lseek64", "lstat", "lstat64", "lutimes", "madvise", "main", "makecontext", "mallinfo", "xmalloc", "malloc",
			"mallopt", "matherr", "mblen", "mbrlen", "mbrtowc", "mbsinit", "mbsnrtowcs", "mbsrtowcs", "mbstowcs",
			"mbtowc", "mcheck", "memalign", "memccpy", "memchr", "memcmp", "memcpy", "memfrob", "memmem", "memmove",
			"mempcpy", "memrchr", "memset", "merge", "mkdir", "mkdtemp", "mkfifo", "mknod", "mkstemp", "mktemp",
			"mktime", "mlock", "mlockall", "mmap", "mmap64", "modf", "modff", "modffn", "modffnx", "modfl", "mount",
			"mprobe", "mrand48", "mrand48_r", "mremap", "msync", "mtrace", "munlock", "munlockall", "munmap",
			"muntrace", "nan", "nanf", "nanfn", "nanfnx", "nanl", "nanosleep", "nearbyint", "nearbyintf", "nearbyintfn",
			"nearbyintfnx", "nearbyintl", "nextafter", "nextafterf", "nextafterfn", "nextafterfnx", "nextafterl",
			"nextdown", "nextdownf", "nextdownfn", "nextdownfnx", "nextdownl", "nexttoward", "nexttowardf",
			"nexttowardl", "nextup", "nextupf", "nextupfn", "nextupfnx", "nextupl", "nftw", "nftw64", "ngettext",
			"nice", "nl_langinfo", "notfound", "nrand48", "nrand48_r", "ntohl", "ntohs", "ntp_adjtime", "ntp_gettime",
			"obstack_1grow", "obstack_1grow_fast", "obstack_alignment_mask", "obstack_alloc", "obstack_base",
			"obstack_blank", "obstack_blank_fast", "obstack_chunk_alloc", "obstack_chunk_free", "obstack_chunk_size",
			"obstack_copy", "obstack_copy0", "obstack_finish", "obstack_free", "obstack_grow", "obstack_grow0",
			"obstack_init", "obstack_int_grow", "obstack_int_grow_fast", "obstack_next_free", "obstack_object_size",
			"obstack_object_size", "obstack_printf", "obstack_ptr_grow", "obstack_ptr_grow_fast", "obstack_room",
			"obstack_vprintf", "offsetof", "on_exit", "open", "open_memstream", "open64", "opendir", "openlog",
			"openpty", "parse_printf_format", "pathconf", "pause", "pclose", "perror", "pipe", "popen",
			"posix_fallocate", "posix_fallocate64", "posix_memalign", "pow", "pow10", "pow10f", "pow10l", "powf",
			"powfn", "powfnx", "powl", "pread", "pread64", "preadv", "preadv2", "preadv64", "preadv64v2", "printf",
			"printf_size", "printf_size_info", "psignal", "pthread_getattr_default_np", "pthread_key_create",
			"pthread_key_delete", "pthread_setattr_default_np", "pthread_setspecific", "ptsname", "ptsname_r", "putc",
			"putc_unlocked", "putchar", "putchar_unlocked", "putenv", "putpwent", "puts", "pututline", "pututxline",
			"putw", "putwc", "putwc_unlocked", "putwchar", "putwchar_unlocked", "pwrite", "pwrite64", "pwritev",
			"pwritev2", "pwritev64", "pwritev64v2", "qecvt", "qecvt_r", "qfcvt", "qfcvt_r", "qgcvt", "qsort", "raise",
			"rand", "rand_r", "random", "random_r", "rawmemchr", "read", "readdir", "readdir_r", "readdir64",
			"readdir64_r", "readlink", "readv", "realloc", "xrealloc", "reallocarray", "realpath", "recv", "recvfrom",
			"regcomp", "regerror", "regexec", "regfree", "register_printf_function", "remainder", "remainderf",
			"remainderfn", "remainderfnx", "remainderl", "remove", "rename", "return", "rewind", "rewinddir", "rindex",
			"rint", "rintf", "rintfn", "rintfnx", "rintl", "rmdir", "round", "roundeven", "roundevenf", "roundevenfn",
			"roundevenfnx", "roundevenl", "roundf", "roundfn", "roundfnx", "roundl", "rpmatch", "s_isblk", "s_ischr",
			"s_isdir", "s_isfifo", "s_islnk", "s_isreg", "s_issock", "s_typeismq", "s_typeissem", "s_typeisshm",
			"scalb", "scalbf", "scalbl", "scalbln", "scalblnf", "scalblnfn", "scalblnfnx", "scalblnl", "scalbn",
			"scalbnf", "scalbnfn", "scalbnfnx", "scalbnl", "scandir", "scandir64", "scanf", "sched_get_priority_max",
			"sched_get_priority_min", "sched_getaffinity", "sched_getparam", "sched_getscheduler",
			"sched_rr_get_interval", "sched_setaffinity", "sched_setparam", "sched_setscheduler", "sched_yield",
			"secure_getenv", "seed48", "seed48_r", "seekdir", "select", "sem_close", "sem_destroy", "sem_getvalue",
			"sem_init", "sem_post", "sem_timedwait", "sem_trywait", "sem_unlink", "sem_wait", "semctl", "semget",
			"semop", "semtimedop", "send", "sendto", "setbuf", "setbuffer", "setcontext", "setdomainname", "setegid",
			"setenv", "seteuid", "setfsent", "setgid", "setgrent", "setgroups", "sethostent", "sethostid",
			"sethostname", "setitimer", "setjmp", "setkey", "setkey_r", "setlinebuf", "setlocale", "setlogmask",
			"setmntent", "setnetent", "setnetgrent", "setpayload", "setpayloadf", "setpayloadfn", "setpayloadfnx",
			"setpayloadl", "setpayloadsig", "setpayloadsigf", "setpayloadsigfn", "setpayloadsigfnx", "setpayloadsigl",
			"setpgid", "setpgrp", "setpriority", "setprotoent", "setpwent", "setregid", "setreuid", "setrlimit",
			"setrlimit64", "setservent", "setsid", "setsockopt", "setstate", "setstate_r", "settimeofday", "setuid",
			"setutent", "setutxent", "setvbuf", "shm_open", "shm_unlink", "shutdown", "sigaction", "sigaddset",
			"sigaltstack", "sigblock", "sigdelset", "sigemptyset", "sigfillset", "siginterrupt", "sigismember",
			"siglongjmp", "sigmask", "signal", "signbit", "significand", "significandf", "significandl", "sigpause",
			"sigpending", "sigprocmask", "sigsetjmp", "sigsetmask", "sigstack", "sigsuspend", "sin", "sincos",
			"sincosf", "sincosfn", "sincosfnx", "sincosl", "sinf", "sinfn", "sinfnx", "sinh", "sinhf", "sinhfn",
			"sinhfnx", "sinhl", "sinl", "sleep", "snprintf", "socket", "socketpair", "sprintf", "sqrt", "sqrtf",
			"sqrtfn", "sqrtfnx", "sqrtl", "srand", "srand48", "srand48_r", "srandom", "srandom_r", "sscanf", "ssignal",
			"stat", "stat64", "stime", "stpcpy", "stpncpy", "strcasecmp", "strcasestr", "strcat", "strchr", "strchrnul",
			"strcmp", "strcoll", "strcpy", "strcspn", "strdup", "strdupa", "strerror", "strerror_r", "strfmon",
			"strfromd", "strfromf", "strfromfn", "strfromfnx", "strfroml", "strfry", "strftime", "strlen",
			"strncasecmp", "strncat", "strncmp", "strncpy", "strndup", "strndupa", "strnlen", "strpbrk", "strptime",
			"strrchr", "strsep", "strsignal", "strspn", "strstr", "strtod", "strtof", "strtofn", "strtofnx",
			"strtoimax", "strtok", "strtok_r", "strtol", "strtold", "strtoll", "strtoq", "strtoul", "strtoull",
			"strtoumax", "strtouq", "strverscmp", "strxfrm", "stty", "success", "sun_len", "swapcontext", "swprintf",
			"swscanf", "symlink", "sync", "syscall", "sysconf", "sysctl", "syslog", "system", "sysv_signal", "tan",
			"tanf", "tanfn", "tanfnx", "tanh", "tanhf", "tanhfn", "tanhfnx", "tanhl", "tanl", "tcdrain", "tcflow",
			"tcflush", "tcgetattr", "tcgetpgrp", "tcgetsid", "tcsendbreak", "tcsetattr", "tcsetpgrp", "tdelete",
			"tdestroy", "telldir", "temp_failure_retry", "tempnam", "textdomain", "tfind", "tgamma", "tgammaf",
			"tgammafn", "tgammafnx", "tgammal", "time", "timegm", "timelocal", "times", "tmpfile", "tmpfile64",
			"tmpnam", "tmpnam_r", "toascii", "tolower", "totalorder", "totalorderf", "totalorderfn", "totalorderfnx",
			"totalorderl", "totalordermag", "totalordermagf", "totalordermagfn", "totalordermagfnx", "totalordermagl",
			"toupper", "towctrans", "towlower", "towupper", "trunc", "truncate", "truncate64", "truncf", "truncfn",
			"truncfnx", "truncl", "tryagain", "tsearch", "ttyname", "ttyname_r", "twalk", "tzset", "ufromfp",
			"ufromfpf", "ufromfpfn", "ufromfpfnx", "ufromfpl", "ufromfpx", "ufromfpxf", "ufromfpxfn", "ufromfpxfnx",
			"ufromfpxl", "ulimit", "umask", "umount", "umount2", "uname", "unavail", "ungetc", "ungetwc", "unlink",
			"unlockpt", "unsetenv", "updwtmp", "utime", "utimes", "utmpname", "utmpxname", "va_arg", "va_copy",
			"va_end", "va_start", "valloc", "vasprintf", "verr", "verrx", "versionsort", "versionsort64", "vfork",
			"vfprintf", "vfscanf", "vfwprintf", "vfwscanf", "vlimit", "vprintf", "vscanf", "vsnprintf", "vsprintf",
			"vsscanf", "vswprintf", "vswscanf", "vsyslog", "vtimes", "vwarn", "vwarnx", "vwprintf", "vwscanf", "wait",
			"wait3", "wait4", "waitpid", "warn", "warnx", "wcoredump", "wcpcpy", "wcpncpy", "wcrtomb", "wcscasecmp",
			"wcscat", "wcschr", "wcschrnul", "wcscmp", "wcscoll", "wcscpy", "wcscspn", "wcsdup", "wcsftime", "wcslen",
			"wcsncasecmp", "wcsncat", "wcsncmp", "wcsncpy", "wcsnlen", "wcsnrtombs", "wcspbrk", "wcsrchr", "wcsrtombs",
			"wcsspn", "wcsstr", "wcstod", "wcstof", "wcstofn", "wcstofnx", "wcstoimax", "wcstok", "wcstol", "wcstold",
			"wcstoll", "wcstombs", "wcstoq", "wcstoul", "wcstoull", "wcstoumax", "wcstouq", "wcswcs", "wcsxfrm",
			"wctob", "wctomb", "wctrans", "wctype", "wexitstatus", "wifexited", "wifsignaled", "wifstopped", "wmemchr",
			"wmemcmp", "wmemcpy", "wmemmove", "wmempcpy", "wmemset", "wordexp", "wordfree", "wprintf", "write",
			"writev", "wscanf", "wstopsig", "wtermsig", "y0", "y0f", "y0fn", "y0fnx", "y0l", "y1", "y1f", "y1fn",
			"y1fnx", "y1l", "yn", "ynf", "ynfn", "ynfnx", "ynl").stream().collect(Collectors.toSet());
}
