name: Build latest development release (Windows)

on:
  push:
    branches:
    - master2.x
    
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'
        
    - name: Build distribution
      working-directory: kam1n0-builds/windows/
      run: ./build-distribution.bat
      
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build installer
      working-directory: kam1n0-builds/windows/
      run: |
        $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
        light.exe
        heat.exe
        where heat.exe
        ./build-installers.bat
      
    - name: Check output
      working-directory: kam1n0-builds/windows/bins/installer/
      run: dir 

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly-action"
        prerelease: true
        title: "Latest development build from master2.x"
        files: |
          LICENSE.txt
          kam1n0-builds/windows/bins/installer/*.exe 
